### ISSUE TITLE
Review 5: CompareProjections.jsx and AuditedFSCollection.js

### ISSUE THREAD

**Issue by bksnelson** [Team-Half-and-Half/spirebooks#113]
## Overview

Please pay attention too:
* JavaScript issues
* React components

## Review Branch

[review-5](https://github.com/Team-Half-and-Half/spirebooks/tree/review-5)

## Files to review

* [CompareProjections.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/review-5/app/imports/ui/pages/CompareProjections.jsx)
* [AuditedFSCollection.js](https://github.com/Team-Half-and-Half/spirebooks/blob/review-5/app/imports/api/spreadsheet/AudtiedFSCollection.js)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/main/checklists/react-checklist.md)

## Due date

Monday, 10/14/2024

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by t-tirabassi** [comment]
**CompareProjections.jsx:**

Design-08/01: Between lines 47-86, the dropdowns for selectedChart1 and selectedChart2 have the same code and could be refactored into a separate component or maybe a function to avoid repetition.

Design-05: The comments within lines 16-31 could probably be removed since what the code does is clear.

REACT-06: On line 12, useTracker should probably be replaced with withTracker.

**AuditedFS.js:**

Design-07/09: The schemas within AuditedFS.js could be made into a separate component or individual subcomponents for reusability and readability.

ESLINT-01: The comments that disable eslint on lines 309 and 329 should be removed and can be fixed through renaming the parameters within the functions.

REACT-04: The dumpOne method on line 418 could be destructured into a single const and return rather than a const for each property.

**Comment by caspascual** [comment]
CompareProjections.jsx

L44-87: Design-01: Chart cards could be made into a component

AuditedFSCollection.js

L12-267: Design-09: Maybe move these schemas into utilities

L418, 431: JS-04: Use object deconstruction to reduce the assignments

**Comment by PaytonHAH** [comment]
CompareProjections.jsx
Design-08: Ensure code is DRY
 Dropdown Component repeated multiple times, possible made into a separate dropdown 
 component for reusability.

AudtiedFSCollection.js
Design-08: Ensure code is DRY
 Schemas can be made separate to be utilized by other spreadsheet collections to reduce 
 duplication. Audited FS pulls from both parts of the balance/budget sheets so making 
 separate components could be used twice instead.

**Comment by jsapolu99** [comment]
CompareProjections.jsx
Design-01: Can you refactor to reduce duplication?
Lines 25-29, 31-35: Duplication of dropdown logic
These lines handle the state and functionality for two nearly identical dropdowns. You can refactor this into a single reusable function and use it for both dropdowns.

AuditedFSColection.js
Design-08: Ensure code is DRY
Lines 228-243, 244-258
The publish methods (subscribeAuditedFS and subscribeAuditedFSAdmin) have similar structures but differ only by the user role and publication name. This is a duplication of logic that can be refactored.
Suggestion: Create a helper function to generalize the logic:

**Comment by samallari** [comment]
CompareProjections.jsx
- repetitive code for dropdown menu, can try to refactor into its own component

AuditedFSCollection.js
- avoid disabling eslint
- 418, 431: use object deconstruction to reduce the assignments

**Comment by PaytonHAH** [comment]
Overview of Review Meeting
CompareProjections.jsx:
- Convert Dropdowns into a reusable component
AuditedFSCollection.js:
- Fix file name from AudtiedFSCollection.js to AuditedFSCollection.js
- Implement Object Deconstruction to reduce assignments
