### ISSUE TITLE
Review: 10 ImportFunctions.js and AuditedBalanceImportFunc.js

### ISSUE THREAD

**Issue by caspascual** [Team-Half-and-Half/spirebooks#162]
## Overview 
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-10

## Files to review

* [ImportFunctions.js](https://github.com/Team-Half-and-Half/spirebooks/blob/review-10/app/imports/ui/utilities/ImportFunctions.js)
* [AuditedBalanceImportFunc.js](https://github.com/Team-Half-and-Half/spirebooks/blob/review-10/app/imports/ui/utilities/AuditedBalanceImportFunc.js)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/main/checklists/react-checklist.md)

## Due date

Monday, 11/18/2024

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by caspascual** [comment]
ImportFunctions.js

L51-59: Design-02: Can we remove the nested if blocks?

AuditedBalanceImportFunc.js

JS-07: Remove all console logs

JS-03: Can spread be used to make it cleaner?

**Comment by samallari** [comment]
ImportFunction.js
- LN 51-52: Can condense if statement into 1 line

AuditedBalanceImportFunc.js
- Remove console logs
- LN 4: Should export and file name match?

**Comment by t-tirabassi** [comment]
**ImportFunctions.js:**

Design-05: A lot of the comments detailing the code can be removed since much of it is self-explanatory.

**AuditedBalanceImportFunc.js:**

JS-07: Remove the console.log statements.

JS-01: The export auditedBalanceImport should be renamed to auditedBalanceImportFunc so that it matches the file name.

**Comment by beydlern** [comment]
**ImportFunction.js**

Detailed comments describing the complicated sections of the code would bolster its clarity.

**AuditedBalanceImportFunc.js**

All console.log statements should be removed.

L4: Exported name should match file name.

**Comment by PaytonHAH** [comment]
### ImportFunction.js

1. Design-07: Ensure code is readable/Design-05: Ensure comments are appropriate
While the explanations through comments are there, maybe have big chunks of comments that explain sections of the code as a whole rather than comments explaining each individual parts of those sections. Some code segments are self explanatory.  

### AuditedBalanceImportFunc.js
1. JS-07: Avoid console.logs
3. Export "auditedBalanceImport" should match the file

**Comment by samallari** [comment]
### Review Overview
ImportFunctions.js
- New issue: Cleanup ImportFunctions.js
ensure code is readable, i.e. explain sections of the code as a whole instead of individual parts, remove nested if block

AuditedBalanceImportFunc.js
- New issue: Cleanup AuditedBalanceImportFunc.js
remove console.log statements, export name should match file name
