### ISSUE TITLE
Review: 11 Dashboard.jsx and InputABS.jsx

### ISSUE THREAD

**Issue by caspascual** [Team-Half-and-Half/spirebooks#172]
## Overview 
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-11

## Files to review

* [Dashboard.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/review-11/app/imports/ui/pages/Dashboard.jsx)
* [InputABS.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/review-11/app/imports/ui/pages/InputABS.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/main/checklists/react-checklist.md)

## Due date

Monday, 11/25/2024

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by XavierBurt** [comment]
Dashboard.jsx:

The constants for the table can probably be moved to another file

InputABS.jsx

Remove the commented out imports
Use multi line comments instead of multiple single line comments (ex lines 21-25)
There might be a better way to do the text field. Not sure honestly but it's a lot of long repeated code. Maybe can make a method?

**Comment by samallari** [comment]
Dashboard.jsx
- LN 137: would be better to pass data into DashboardTable to render data dynamically instead of having static data

InputABS.jsx
- maybe split text fields into their own components and import them into InputABS for better readability?

**Comment by caspascual** [comment]
Dashboard.jsx

L25-61: Design-09: Should move these functions into their own file in utilities.

InputABS.jsx

L64-158: Design-01: All text field use label={false} disabled, are we able to make this into a class in CSS to remove redundancy?

L18-19: Design-05: Don’t see any reason to keep these comments

L14, L21: Design-05: Stuff comments, remove.

L43. ESLINT-02: Remove stuff ID, make new ID for testcafe.

**Comment by t-tirabassi** [comment]
**Dashboard.jsx:**

Design-07: The container in the return statement could be made into a component and then imported into the dashboard page.

Design-09: The constants for the table could be moved into utilities to be reused.

**InputABS.jsx:**

Design-05: The commented out imports and constants should be removed. Other unnecessary comments throughout the code should also be removed.

REACT-01: Move all the text fields in the balance sheet form into its own component so that the code is more readable.

**Comment by beydlern** [comment]
**Dashboard.jsx:**

- L25-61: Place these functions into a functions file under the utilities folder section for reusability.

**InputABS.jsx**

- Remove unnecessary comments (commented out import functions and variables)
- Remove all Stuff references
